# Generated by Django 3.1 on 2020-09-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
