# Generated by Django 3.1 on 2020-09-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_buying'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buying',
            new_name='Purchase',
        ),
    ]
