# Generated by Django 3.1 on 2020-09-22 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_auto_20200921_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='laces',
        ),
        migrations.AddField(
            model_name='sneaker',
            name='shoelaces',
            field=models.ManyToManyField(to='main_app.Shoelace'),
        ),
        migrations.AddField(
            model_name='sneaker',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sneaker')),
            ],
        ),
    ]
